@host = http://localhost:5000/api

# @name Create Student
POST {{host}}/student
Accept: application/json

> {%
    let id = jsonPath(response.body, "$.id");
    client.global.set("studentId", id);
%}

###
# @name Update Student
PUT {{host}}/student/{{studentId}}
Accept: application/json

###
# @name Get Student
GET {{host}}/student/{{studentId}}
Accept: application/json